create or replace TABLE EXPENSE_TRACKER (
	ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	USERNAME VARCHAR(255),
	FREQUENCY VARCHAR(50),
	EXPENSE_TYPE VARCHAR(255),
	NOTES VARCHAR(255),
	AMOUNT NUMBER(18,2),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (ID)
);

create or replace TABLE INCOME_TRACKER (
	ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	USERNAME VARCHAR(255),
	FREQUENCY VARCHAR(50),
	AMOUNT NUMBER(18,2),
	INCOME_SOURCE VARCHAR(255),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (ID)
);
create or replace TABLE SAVINGS_GOAL_TRACKER (
	USERNAME VARCHAR(255),
	SAVINGSGOALITEM VARCHAR(255),
	SAVINGSGOALAMOUNT NUMBER(18,2),
	ALLOCATIONPERCENTAGE NUMBER(5,2),
	MONTHLYDISPOSABLEINCOME NUMBER(18,2),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
create or replace TABLE USERS (
	FIRSTNAME VARCHAR(16777216),
	LASTNAME VARCHAR(16777216),
	USERNAME VARCHAR(16777216),
	PASSWORD VARCHAR(16777216),
	EMAIL VARCHAR(16777216)
);