stages:
  - build
  - test
  - deploy

variables:
  TEST_REPORTS: "tests/reports"

before_script:
  - echo "Starting the pipeline..."

build:
  stage: build
  script:
    - echo "Compiling the code..."
    - make build
  artifacts:
    paths:
      - build/
  tags:
    - linux

test:
  stage: test
  script:
    - echo "Running unit tests..."
    - mkdir -p $TEST_REPORTS
    - pytest --junitxml=$TEST_REPORTS/report.xml
  artifacts:
    when: always
    paths:
      - $TEST_REPORTS
  tags:
    - linux
  allow_failure: false

deploy:
  stage: deploy
  script:
    - echo "Deploying the application..."
    - make deploy
  tags:
    - linux
  when: manual
