name: CI/CD Pipeline

on:
  push:
    branches:
      - MBWorkflow
  pull_request:
    branches:
      - MBWorkflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build
        run: |
          echo "Building the project..."
          make build

      - name: Save build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build/

      - name: Run tests
        run: |
          echo "Running unit tests..."
          mkdir -p tests/reports
          pytest --junitxml=tests/reports/report.xml

      - name: Save test reports
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: tests/reports/

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build/

      - name: Deploy
        run: |
          echo "Deploying the application..."
          make deploy
