name: Python CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: self-hosted 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download and Extract Python
      run: |
        wget https://github.com/actions/python-versions/releases/download/3.10.11-4626646535/python-3.10.11-win32-x64.zip -O python.zip
        mkdir python
        unzip python.zip -d python
        export PATH=$PWD/python:$PATH

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask snowflake-connector-python datetime
